# Welcome to Jekyll!
# This config file is meant for settings that affect your whole blog

# Site settings
include: 
  - _pages
  - _portfolio
  - _posts

title: Professional Portfolio
email: paspring@gmail.com
description: >-
  Explore my professional portfolio to discover my work as a Data Scientist. 
  Delve into my career background in the "About" section, check out my projects highlighting my skills and creativity, 
  and read my latest insights in the "Blog" section. This site is a curated collection of my experiences, projects, and thoughts in the realm of data science.
baseurl: ""
url: "https://paspring.github.io"
github_username: paspring

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Code block fixes (NEW)
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

minimal_mistakes:
  skin: "default"
  html:
    compress: false  # Disable to prevent layout issues

# Layout settings
classes: wide
layout: splash
paginate: 3
paginate_path: "/page:num/"

# Author profile
author:
  name: "Pablo Andres<br>Spring Flores, M.S."
  avatar: "/assets/images/profiles.jpeg"
  bio: "Senior Data Analyst<br>10+ Years of Experience"
  location: "Jersey City, NJ"
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/paspring/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/paspring"

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  continuous_learning:
    output: true
    permalink: /continuous-learning/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      related: true
      toc: true

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
