# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

include: 
  - _pages
  - _portfolio
  - _posts

title: Professional Portfolio
email: paspring@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Explore my professional portfolio to discover my work as a Data Scientist. 
  Delve into my career background in the "About" section, check out my projects highlighting my skills and creativity, 
  and read my latest insights in the "Blog" section. This site is a curated collection of my experiences, projects, and thoughts in the realm of data science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paspring.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  paspring

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

classes: wide
layout: splash
paginate: 3
paginate_path: "/page:num/"

author:
  name: "Pablo Andres
  <br> 
  Spring Flores, M.S."
  avatar: "/assets/images/profiles.jpeg"
  bio: "Senior Data Analyst 
  <br>
  Data Scientist
  <br>
  10 Years of Experience 
  <br>
  (3 Years in the USA)" # Note: Markdown is allowed
  location: "Jersey City, NJ"
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/paspring/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/paspring"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  continuous_learning:
    output: true
    permalink: /continuous-learning/:path/ 
  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      related: true
      toc: true